# The Docker image that will be used to build your app
image: blog
create-pages:
  pages:
    # The folder that contains the files to be exposed at the Page URL
    publish: public
    path_prefix: "blog"
  rules:
    # This ensures that only pushes to the default branch will trigger
    # a pages deploy
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
